export default [
  {
    id: 1,
    name: "Babka",
    price: 9.95,
    description: "Buttery, sweet and brioche-like crumb",
    ideas: "Perfect as-is or with a glass of milk",
    flavor: "Chocolate",
    ingredients:
      "flour, yeast, sugar, eggs, milk, butter, salt, cinnamon, cocoa powder, dark chocolate",
    url: "assets/images/unsplash12.jpg",
    type: "pastry",
  },
  {
    id: 2,
    name: "Cardamom Bun",
    price: 3.95,
    description: "Sweet, aromatic, fluffy and airy texture",
    ideas: "Perfect as-is",
    flavor: "Plain",
    ingredients:
      "flour, milk, yeast, ground cardamom, brown sugar, butter, salt",
    url: "assets/images/unsplash11.jpg",
    type: "pastry",
  },
  {
    id: 3,
    name: "Challah Loaf",
    price: 8.95,
    description: "Pleasant sweet flavor and a soft, fluffy texture",
    ideas:
      "Perfect sliced and spread with butter and jam or used for French toast or bread pudding",
    flavor: "Sesame",
    ingredients:
      "flour, butter, eggs, sugar, vegetable oil, honey, yeast, water, sesame seeds",
    url: "assets/images/unsplash2.jpg",
    type: "bread",
  },
  {
    id: 4,
    name: "Ciabatta Loaf",
    price: 6.95,
    description: "Light and airy bread with a slightly chewy, crispy crust",
    ideas: "Perfect for garlic bread, sandwiches, paninis, or as table bread",
    flavor: "Roasted Garlic",
    ingredients: "flour, yeast, olive oil, salt, water, garlic",
    url: "assets/images/unsplash15.jpg",
    type: "bread",
  },
  {
    id: 5,
    name: "Cinnamon Roll",
    price: 3.95,
    description: "Creamy, doughy, sweet and decadent",
    ideas: "Perfect as-is or with a glass of milk",
    flavor: "Cream Cheese",
    ingredients:
      "flour, sugar, milk, butter, yeast, eggs, salt, cinnamon, cardamom, nutmeg, cream cheese",
    url: "assets/images/unsplash17.jpg",
    type: "pastry",
  },
  {
    id: 6,
    name: "Croissant",
    price: 2.95,
    description: "Buttery, flaky and sweet",
    ideas: "Perfect as-is or toasted",
    flavor: "Chocolate",
    ingredients: "flour, yeast, butter, milk, chocolate, sugar, salt",
    url: "assets/images/unsplash7.jpg",
    type: "pastry",
  },
  {
    id: 7,
    name: "Hokkaido Milk Loaf",
    price: 10.95,
    description: "Milky-sweet flavor and a feathery soft texture",
    ideas: "Perfect as-is or toasted and smeared with butter and jam",
    flavor: "Plain",
    ingredients: "flour, sugar, yeast, milk, butter, milk powder, egg, salt",
    url: "assets/images/unsplash13.jpg",
    type: "bread",
  },
  {
    id: 8,
    name: "Hokkaido Milk Roll",
    price: 3.95,
    description: "Milky-sweet flavor and a feathery soft texture",
    ideas: "Perfect as-is or toasted and smeared with butter and jam",
    flavor: "Glazed",
    ingredients: "flour, sugar, yeast, milk, butter, milk powder, egg, salt",
    url: "assets/images/unsplash9.jpg",
    type: "pastry",
  },

  {
    id: 9,
    name: "Multi-Grain Loaf",
    price: 7.95,
    description:
      "Subtle sweetness, unique texture, complex and slightly nutty flavor",
    ideas: "Perfect for breakfast toasts or sandwiches",
    flavor: "Plain",
    ingredients:
      "cracked rye, barley, flax, millet, oats, spelt, wheat, whole-wheat flour, flaxseed, quinoa, sunflower seeds, egg white",
    url: "assets/images/unsplash3.jpg",
    type: "bread",
  },
  {
    id: 10,
    name: "Pita Bread",
    price: 1.95,
    description: "Light with a semi-dry and dense, chewy bite",
    ideas:
      "Perfect for Greek souvlaki, Middle Eastern falafel sandwich, or served with kebabs",
    flavor: "Plain",
    ingredients: "flour, salt, yeast, water, sugar, olive oil",
    url: "assets/images/unsplash24.jpg",
    type: "bread",
  },
  {
    id: 11,
    name: "Pumperknickel Loaf",
    price: 7.95,
    description: "Nutty flavor and a slightly sweet",
    ideas: "Perfect toasted with butter or sandwiches",
    flavor: "Plain",
    ingredients: "rye flour, molasses, cocoa powder, wheat flour, cornmeal",
    url: "assets/images/unsplash10.jpg",
    type: "bread",
  },
  {
    id: 12,
    name: "Sourdough Loaf",
    price: 10.95,
    description: "Slightly tangy flavor, crispy crust, and airy-chewy crumb",
    ideas:
      "Perfect for toast, sandwich bread, or accompaniment to a charcuterie board",
    flavor: "Plain",
    ingredients: "sourdough starter, flour, salt, water, olive oil",
    url: "assets/images/unsplash4.jpg",
    type: "bread",
  },
];
