export default [
  {
    id: 1,
    name: "Babka Slice",
    price: 3.45,
    description: "Creamy, doughy, sweet and decadent.",
    ideas: "Perfect as-is or with a glass of milk.",
    flavor: "Chocolate",
  },
  {
    id: 2,
    name: "Bagel",
    price: 2.45,
    description: "Somewhat sweet or somewhat salty, chewy crumb.",
    ideas:
      "Perfect as an open-faced toast-like meal or as a breakfast sandwich.",
    flavor: "Blueberry",
  },
  {
    id: 3,
    name: "Baguette",
    price: 5.15,
    description:
      "Crispy crust and soft chewy crumb, balanced flavor and mild acidity.",
    ideas:
      "Perfect with butter, cheese, and cured meats, or alongside charcuterie boards and butter boards.",
    flavor: "Plain",
  },
  {
    id: 4,
    name: "Brioche Loaf",
    price: 8.25,
    description: "Sweet, fluffy and airy texture.",
    ideas:
      "Perfect as French toast, or as a slice of bread served with butter or jam.",
    flavor: "Plain",
  },
  {
    id: 5,
    name: "Challah Loaf",
    price: 8.35,
    description: "Pleasant sweet flavor and a soft, fluffy texture.",
    ideas:
      "Perfect sliced and spread with butter and jam or used for French toast or bread pudding.",
    flavor: "Sesame",
  },
  {
    id: 6,
    name: "Ciabatta Loaf",
    price: 5.85,
    description: "Light and airy bread with a slightly chewy, crispy crust.",
    ideas: "Perfect for garlic bread, sandwiches, paninis, or as table bread.",
    flavor: "Roasted Garlic",
  },
  {
    id: 7,
    name: "Cinnamon Roll",
    price: 3.75,
    description: "Creamy, doughy, sweet and decadent.",
    ideas: "Perfect as-is or with a glass of milk.",
    flavor: "Frosted Pecan",
  },
  {
    id: 8,
    name: "Croissant",
    price: 3.45,
    description: "Buttery, flaky and slightly sweet.",
    ideas: "Perfect as-is, toasted or for breakfast sandwiches.",
    flavor: "Almond",
  },
  {
    id: 9,
    name: "Foccacia Loaf",
    price: 6.65,
    description: "Soft, buttery, airy interior and crispy crust.",
    ideas: "Perfect alongside olive oil or made into a panini.",
    flavor: "Rosemary",
  },
  {
    id: 10,
    name: "Hokkaido Milk Loaf",
    price: 10.65,
    description: "Milky-sweet flavor and a feathery soft texture.",
    ideas: "Perfect as-is or toasted and smeared with butter and jam.",
    flavor: "Plain",
  },
  {
    id: 11,
    name: "Multi-Grain Loaf",
    price: 7.75,
    description:
      "Subtle sweetness, unique texture, complex and slightly nutty flavor.",
    ideas: "Perfect for breakfast toasts or sandwiches.",
    flavor: "Cracked rye, oat, spelt and sunflower blend",
  },
  {
    id: 12,
    name: "Pita",
    price: 2.25,
    description: "Light with a semi-dry and dense, chewy bite.",
    ideas:
      "Perfect for Greek souvlaki, Middle Eastern falafel sandwich, or served with kebabs.",
    flavor: "Plain",
  },
  {
    id: 13,
    name: "Pumperknickel Loaf",
    price: 8.55,
    description: "Nutty flavor and a slightly sweet.",
    ideas: "Perfect toasted with butter or sandwiches.",
    flavor: "Plain",
  },
  {
    id: 14,
    name: "Soft Pretzel",
    price: 4.25,
    description: "Aromatic, chewy and slight malty flavor.",
    ideas: "Perfect as-is or dipped in cheese dip.",
    flavor: "Plain",
  },
  {
    id: 15,
    name: "Sourdough Loaf",
    price: 9.25,
    description: "Slightly tangy flavor, crispy crust, and airy-chewy crumb.",
    ideas:
      "Perfect for toast, sandwich bread, or accompaniment to a charcuterie board.",
    flavor: "Plain",
  },
];
